#!/usr/bin/env python3

import base64
import json
import os
import pathlib
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Iterable
from copy import deepcopy

import kubernetes
import openshift.dynamic
import openshift.dynamic.exceptions
import urllib3
import yaml
from openshift.dynamic.exceptions import NotFoundError

SCRIPT_DIR = sys.path[0] if os.path.isdir(sys.path[0]) else os.path.dirname(sys.path[0])

def str_presenter(dumper, data):
    if isinstance(data, str):
        if '\n' in data:
            return dumper.represent_scalar('tag:yaml.org,2002:str', data, style='|')

    return dumper.represent_scalar('tag:yaml.org,2002:str', data)

yaml.add_representer(str, str_presenter)

def del_extra_keys(cur, last, new):
    """Delete keys in cur which are neither present in last nor in new, i.e. keys managed by the cluster."""
    if isinstance(cur, dict):
        for key, val in list(cur.items()):
            if last and key in last or new and key in new:
                del_extra_keys(val, last.get(key) if last else None, new.get(key) if new else None)
            else:
                del cur[key]
    elif isinstance(cur, list):
        for i, cur_item in enumerate(cur):
            del_extra_keys(cur_item, last[i] if last and i < len(last) else None, new[i] if new and i < len(new) else None)

def add_default_keys(cur, last):
    """Add keys to cur which are present in last but missing in cur, i.e. keys that contain default values."""
    if isinstance(last, dict):
        for last_key, last_val in list(last.items()):
            if cur and last_key in cur:
                add_default_keys(cur.get(last_key) if cur else None, last_val)
            else:
                cur[last_key] = last_val
    elif isinstance(last, list):
        for i, last_item in enumerate(last):
            add_default_keys(cur[i] if cur and i < len(cur) else None, last_item)


# Disable SSL warnings: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3.disable_warnings()

if 'KUBERNETES_PORT' in os.environ:
    kubernetes.config.load_incluster_config()
    namespace = pathlib.Path('/var/run/secrets/kubernetes.io/serviceaccount/namespace').read_text()
else:
    kubernetes.config.load_kube_config()
    _, active_context = kubernetes.config.list_kube_config_contexts()
    namespace = active_context['context']['namespace']

if len(sys.argv) > 1:
    namespace = sys.argv[1]

k8s_client = kubernetes.client.api_client.ApiClient(kubernetes.client.Configuration())
dyn_client = openshift.dynamic.DynamicClient(k8s_client)

with tempfile.TemporaryDirectory() as tmpdir:
    os.makedirs(f"{tmpdir}/new", exist_ok=True)
    os.makedirs(f"{tmpdir}/cur", exist_ok=True)
    documents = yaml.safe_load_all(sys.stdin)
    for doc in documents:
        objects = doc.get('items', None) or [doc]
        for obj in objects:
            obj['metadata']['namespace'] = namespace
            if not 'annotations' in obj['metadata']:
                obj['metadata']['annotations'] = {}

            if obj['kind'] == 'Secret':
                for key, value in obj.get('stringData', {}).items():
                    obj.setdefault('data', {})[key] = base64.b64encode(value.encode('ascii')).decode('ascii')
                obj.pop('stringData', None)

            with open(f"{tmpdir}/new/{obj['kind']}_{obj['metadata']['name']}.yaml", 'w+') as file:
                yaml.dump(obj, file, default_flow_style=False, width=float("inf"))

            obj_client = dyn_client.resources.get(api_version = obj['apiVersion'], kind = obj['kind'])
            with open(f"{tmpdir}/cur/{obj['kind']}_{obj['metadata']['name']}.yaml", 'w+') as file:
                try:
                    current = obj_client.get(name=obj['metadata']['name'], namespace=namespace, export=True).to_dict()
                    last_applied = json.loads(current['metadata'].get('annotations', {}).get('kubectl.kubernetes.io/last-applied-configuration', '{}'))
                    current['metadata'].get('annotations', {}).pop('kubectl.kubernetes.io/last-applied-configuration', None)
                    del_extra_keys(current, last_applied, obj)
                    add_default_keys(current, last_applied)

                    yaml.dump(current, file, default_flow_style=False, width=float("inf"))
                except NotFoundError:
                    pass

    # subprocess.Popen(f"ls -l {tmpdir}/cur", shell=True)

    color_opt = '--color' #if sys.stdout.isatty() else ''
    p = subprocess.Popen(f"cd {tmpdir} && git --no-pager diff --no-index --no-prefix --minimal {color_opt} cur new | {SCRIPT_DIR}/diff-highlight", shell=True)
    p.communicate()

